name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven      
    - name: Run tests
      run: mvn test
      continue-on-error: true    

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/cucumberReports.html
        
    - name: Send test report email
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Test Report
        body: Test results attached.
        to: <email adress>
        from: <email adress>
        attachments: target/cucumberReports.html
